apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30005   # Expose SonarQube on a specific NodePort
  type: NodePort
